config/routes.rb
CodabraWorld::Application.routes.draw do

  root :to => 'home#index'

  match '/signup',  to: 'codabras#new', as: :signup
  match '/signin',  to: 'sessions#new', as: :signin
  match '/signout', to: 'sessions#destroy', as: :signout, method: :delete

  resource :session, only: [:new, :create, :destroy]
  resources :passwords, only: [:new, :create, :edit, :update]

  resources :codabras

  resources :battles do
    put 'fight', on: :member
    get 'log', on: :member
  end

  match '/arena', to: 'battles#index', as: :arena

  resources :programs do
    get 'test', on: :member
  end

  match ':name', to: 'codabras#show', as: :profile
  match ':name/edit', to: 'codabras#edit', as: :edit_profile
end

app/models/program.rb
class Program < ActiveRecord::Base

  belongs_to :owner, class_name: 'Codabra'
  belongs_to :battle_type, foreign_key: :battle_class, primary_key: :battle_class

  has_many :won_battles, class_name: 'Battle', foreign_key: :winner_program_id

  validates_presence_of :battle_class
  validates_presence_of :owner_id
  validates_presence_of :name
  validate :check_syntax

  def check_syntax
    execute(nil, "-c")
  end

  def execute(params = nil, opts = nil)
    create_file

    output = Executor::exec("ruby #{opts} #{@tmppath} #{params} 2>&1")
    rc = $?.clone
    unless $?.success?
      errors.add(:code, output)
    end

    remove_file

    [rc, output]
  end

  def wins_count
    self.won_battles.where(public: true).count
  end

private

  def base_file_path
    "/tmp/program-#{self.id}"
  end

  def create_file
    @tmppath = Executor::exec("mktemp #{base_file_path}-XXXXXXXX").chomp

    f = File.open(@tmppath, "w")
    f.write(self.code)
    f.close

    @tmppath
  end

  def remove_file
    File.unlink(@tmppath)
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  before_filter :login_required
  before_filter :ownership_requied, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /programs
  # GET /programs.json
  def index
    @programs = current_codabra.programs.all

    respond_with(@programs)
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_with(@program)
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new
    @battle_types = BattleType.all

    respond_with(@program)
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
    @battle_types = BattleType.all
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = current_codabra.programs.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])
    @battle_types = BattleType.all

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :ok }
    end
  end

  # GET /programs/1/test
  # GET /programs/1/test.json
  def test
    unless @mq
      @mq = Bunny.new('amqp://localhost:5672')
      @mq.start
    end

    program = Program.find(params[:id])
    splinter = Codabra.find_by_name('splinter')

    @battle = current_codabra.battles.new(
      creator_program: program,
      player: splinter,
      player_program: splinter.programs.where(battle_class: program.battle_class).first,
      public: false
    )
    @battle.type = program.battle_class
    @battle.fight

    respond_to do |format|
      if @battle.save
        @mq.exchange('').publish(@battle.id, key: 'codabra.battles')
        format.html { redirect_to battle_path(@battle) }
        format.json { head :ok }
      else
        format.html { redirect_to programs }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def ownership_requied
    redirect_to programs_path unless current_codabra == Program.find(params[:id]).owner
  end

end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :battle %><br />
    <%= f.select :battle_class, @battle_types.collect { |bt| [bt.name, bt.battle_class] } %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <% if @program.new_record? %>
    	<%= f.text_area :code, value: @battle_types.first.code_template, cols: 80 %>
    <% else %>
    	<%= f.text_area :code, cols: 80 %>
    <% end %>
  </div>
  <div class="actions">
    <%= button_submit_tag t(:'links.ok') %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
  	<th>Name</th>
    <th>Battle</th>
    <th>Wins</th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr>
  	<td><%= program.name %></td>
    <td><%= program.battle_type.name %></td>
    <td><%= program.wins_count %></td>
    <td><%= button_group do %>
          <%= button_link_to t(:'links.detail'), program %>
          <%= button_link_to t(:'links.edit'), edit_program_path(program) %>
          <%= button_link_to t(:'links.test'), test_program_path(program) %>
          <%= negative_button_link_to t(:'links.remove'), program, confirm: 'Are you sure?', method: :delete %>
        <% end %>
    </td>

  </tr>
<% end %>
</table>

<br />

<%= button_link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<br />

<p>
  <b>Name:</b> <%= @program.name %>
</p>

<p>
  <b>Battle:</b> <%= @program.battle_type.name %>
</p>

<br />

<pre><%= @program.code %></pre>

<br />

<%= button_group do %>
	<%= button_link_to t(:'links.back'), programs_path %>
	<%= button_link_to t(:'links.edit'), edit_program_path(@program) %>
<% end %>