config/routes.rb
CodabraWorld::Application.routes.draw do

  root :to => 'home#index'

  match '/signup',  to: 'codabras#new', as: :signup
  match '/signin',  to: 'sessions#new', as: :signin
  match '/signout', to: 'sessions#destroy', as: :signout, method: :delete

  resource :session, only: [:new, :create, :destroy]
  resources :passwords, only: [:new, :create, :edit, :update]

  resources :codabras

  resources :battles do
    put 'fight', on: :member
    get 'log', on: :member
  end

  match '/arena', to: 'battles#index', as: :arena

  resources :programs do
    get 'test', on: :member
  end

  match ':name', to: 'codabras#show', as: :profile
  match ':name/edit', to: 'codabras#edit', as: :edit_profile
end

app/models/battle.rb
class Battle < ActiveRecord::Base
  include AASM

  belongs_to :battle_type, foreign_key: :type, primary_key: :battle_class
  belongs_to :creator, class_name: 'Codabra'
  belongs_to :creator_program, class_name: 'Program'
  belongs_to :player, class_name: 'Codabra'
  belongs_to :player_program, class_name: 'Program'
  belongs_to :winner, class_name: 'Codabra'
  belongs_to :winner_program, class_name: 'Program'

  aasm_column :status
  aasm_initial_state :new

  aasm_state :new
  aasm_state :fighting
  aasm_state :finished

  aasm_event :fight do
    transitions from: [:new], to: :fighting
  end

  aasm_event :run do
    transitions from: [:fighting], to: :finished, guard: :do_run
  end

  validates_presence_of :creator_id
  validates_presence_of :creator_program_id
  validates_presence_of :status

  def read_log
    content = nil
    if File.exists?(log_path)
       File.open(log_path, "r") { |f| content = f.read }
    end
    content
  end

protected

  def clear_log
    File.unlink(log_path) if File.exists?(log_path)
  end

  def write_log(message)
    File.open(log_path, "a+") { |f| f.puts(message) }
  end

  def do_run
    nil
  end

private

  def log_path
    "/tmp/battle-log-#{self.id}"
  end

end

app/models/battle/cariba.rb
module CaribaPlayer
  attr_accessor :hp, :block, :attack, :last_attacked, :extra_damage, :program

  def dead?
    self.hp <= 0
  end
end

class Battle::Cariba < Battle

  BODYPARTS = ['head', 'body', 'legs'].freeze

  def do_run
    @players = [self.creator.extend(CaribaPlayer), self.player.extend(CaribaPlayer)]
    @players[0].program = self.creator_program
    @players[1].program = self.player_program
    @players.shuffle!

    self.rounds = 1

    clear_log

    set_start_hp

    while both_are_alive?
      write_log("round \##{self.rounds}")
      do_round
      self.rounds += 1
      save
    end

    if @players[1].dead?
      self.winner = @players[0]
      self.winner_program = @players[0].program
    else
      self.winner = @players[1]
      self.winner_program = @players[1].program
    end

    write_log("#{self.winner.name} win!")

    true
  end

protected

  def both_are_alive?
    not @players[0].dead? and not @players[1].dead?
  end

  def set_start_hp
    @players.each do |p|
      p.hp = p.level * 10
      p.extra_damage = 0
      write_log("#{p.name}'s hp is #{p.hp}")
    end
  end

  def do_round
    do_action('blocks from?')
    do_action('attacks to?')
    do_attack(@players[0], @players[1])
    do_attack(@players[1], @players[0]) unless @players[1].dead?
    do_action('was attacked to')
  end

  def do_action(action)
    @players.each do |p|

      if action == 'was attacked to'
        action += " #{p.last_attacked}"
      end

      rc, output = p.program.execute(action)
      output.chomp!

      if rc.success?
        if BODYPARTS.include?(output)
          case action
          when 'blocks from?'
            p.block = output
            write_log("#{p.name} sets block to #{output}")
          when 'attacks to?'
            p.attack = output
            write_log("#{p.name} tries attack to #{output}")
          end
        else
          write_log("#{p.name} is dulling") unless action.include?('was attacked to')
        end
      else
        write_log("#{p.name} crashs")
      end
    end
  end

  def do_attack(me, enemy)
    return unless BODYPARTS.include?(me.attack)

    if enemy.block == me.attack
      write_log("#{enemy.name} blocks from #{me.name}")
      enemy.last_attacked = nil
      enemy.extra_damage = 0
    else
      enemy.hp -= 1
      if enemy.last_attacked == me.attack
        enemy.extra_damage += 1
        enemy.hp -= enemy.extra_damage
        write_log("#{me.name} bits #{enemy.name} with #{enemy.extra_damage + 1} damage")
      else
        write_log("#{me.name} bits #{enemy.name} with 1 damage")
      end
      enemy.last_attacked = me.attack
      write_log("#{enemy.name} hp decreases to #{enemy.hp}")
    end
  end

end

app/models/battle_type.rb
class BattleType < ActiveRecord::Base
  has_many :battles, foreign_key: :type, primary_key: :battle_class
  has_many :programs, foreign_key: :battle_class, primary_key: :battle_class

  validates :name, presence: true
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController

  before_filter :login_required, except: :index

  respond_to :html, :json

  # GET /battles
  # GET /battles.json
  def index
    @presenter = Battles::IndexPresenter.new(current_codabra)
  end

  # GET /battles/1
  # GET /battles/1.json
  def show
    @battle = Battle.find(params[:id])

    if @battle.public or current_codabra == @battle.creator
      respond_with(@battle)
    end
  end

  # GET /battles/new
  # GET /battles/new.json
  def new
    @battle = Battle.new
    @battle_types = BattleType.all
    @programs = current_codabra.programs

    respond_with(@battle)
  end

  # POST /battles
  # POST /battles.json
  def create
    @battle_types = BattleType.all
    @battle = current_codabra.battles.new(params[:battle])
    @battle.type = params[:battle][:type]

    respond_to do |format|
      if @battle.save
        format.html { redirect_to arena_path, notice: 'Battle was successfully created.' }
        format.json { render json: @battle, status: :created, location: @battle }
      else
        format.html { render :new }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battles/1
  # DELETE /battles/1.json
  def destroy
    @battle = Battle.find(params[:id])
    @battle.destroy

    respond_to do |format|
      format.html { redirect_to battles_url }
      format.json { head :ok }
    end
  end

  # PUT /battles/1/fight
  # PUT /battles/1/fight.json
  def fight
    unless @mq
      @mq = Bunny.new('amqp://localhost:5672')
      @mq.start
    end

    @battle = Battle.find(params[:id])
    @battle.player = current_codabra
    @battle.update_attributes(params[:battle])
    @battle.fight

    respond_to do |format|
      if @battle.save
        @mq.exchange('').publish(@battle.id, key: 'codabra.battles')
        format.html { redirect_to battle_path(@battle) }
        format.json { head :ok }
      else
        format.html { redirect_to arena_path }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /battles/1/log.json
  def log
    @battle = Battle.find(params[:id])

    respond_to do |format|
      format.json { render json: JSON.generate(status: @battle.status, log: @battle.read_log) }
    end
  end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/_battle.html.erb
<tr>
  <td><%= battle.battle_type.name %></td>
  <td><%= link_to battle.creator.name, profile_path(battle.creator.name) %></td>
  <td><%= battle.creator_program.name %></td>
  <td><%= battle.player && link_to(battle.player.name, profile_path(battle.player.name)) || '?' %></td>
  <td><%= battle.player_program && battle.player_program.name || '?' %></td>
  <td><%= battle.status %></td>
  <td><%= battle.winner && link_to(battle.winner.name, profile_path(battle.winner.name)) || '?' %></td>
<% if show_rounds %>
  <td><%= battle.rounds %></td>
<% end %>
<% if logged_in? %>
  <td>
    <%= button_link_to t(:'links.detail'), battle_path(battle) if battle.status != 'new' %>
    <% if current_codabra != battle.creator and battle.status == 'new' %>
      <%= button_group do %>
        <%= form_for(battle, as: :battle, html: { class: 'fight' }, url: fight_battle_path(battle)) do |f| %>
          <%= f.select :player_program_id, @presenter.my_programs.collect { |p| [p.name, p.id] } %>
          <%= button_submit_tag t(:'links.fight') %>
        <% end %>
      <% end %>
    <% end %>
  </td>
  <td>
    <% if current_codabra == battle.creator and battle.status == 'new' %>
      <%= negative_button_link_to t(:'links.remove'), battle_path(battle), confirm: 'Are you sure?', method: :delete %>
    <%end %>
  </td>
<% end %>
</tr>

app/views/battles/_form.html.erb
<%= form_for(@battle) do |f| %>
  <% if @battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% @battle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :type, @battle_types.collect { |bt| [bt.name, bt.battle_class] } %>
  </div>
  <div class="field">
    <%= f.label :program %><br />
    <%= f.select :creator_program_id, @programs.collect { |p| [p.name, p.id] } %>
  </div>
  <div class="actions">
    <%= button_submit_tag t(:'links.ok') %>
  </div>
<% end %>

app/views/battles/_list.html.erb
<h1><%= header %></h1>

  <% unless battles.empty? %>
    <table>
      <tr>
        <th>Type</th>
        <th>Creator</th>
        <th>Program</th>
        <th>Player</th>
        <th>Program</th>
        <th>Status</th>
        <th>Winner</th>
      <% if show_rounds %>
        <th>Rounds</th>
      <% end %>
      <% if logged_in? %>
        <th></th>
        <th></th>
      <% end %>
      </tr>
      <% battles.each do |battle| %>
        <%= render 'battle', battle: battle, show_rounds: show_rounds %>
      <% end %>
    </table>
  <% else %>
    <p>None</p>
  <% end %>

<br />

app/views/battles/edit.html.erb
<h1>Editing battle</h1>

<%= render 'form' %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>

app/views/battles/index.html.erb
<%= render 'list', battles: @presenter.my_battles, header: 'My battles', show_rounds: false if logged_in? %>
<%= render 'list', battles: @presenter.new_battles, header: 'Available battles', show_rounds: false %>
<%= render 'list', battles: @presenter.fighting_battles, header: 'Current battles', show_rounds: true %>
<%= render 'list', battles: @presenter.recent_battles, header: 'Recent battles', show_rounds: true %>

<%= button_link_to 'New Battle', new_battle_path if logged_in? %>

app/views/battles/new.html.erb
<h1>New battle</h1>

<%= render 'form' %>

app/views/battles/show.html.erb
<p id="notice"><%= notice %></p>

<br />

<p>
  <b>Battle:</b> <%= @battle.battle_type.name %>
</p>

<p>
  <b>Creator:</b> <%= @battle.creator.name %> (<%= @battle.creator_program.name %>)
</p>

<p>
  <b>Player:</b> <%= @battle.player.name %> (<%= @battle.player_program.name %>)
</p>

<% if @battle.winner %>
<p>
  <b>Winner:</b> <%= @battle.winner.name %> (<%= @battle.winner_program.name %>)
</p>
<% end %>

<p>
  <b>Status:</b> <%= @battle.status %>
</p>

<br />

<pre id="log">loading...</pre>

<br />

<% if current_codabra == @battle.creator and @battle.status == 'new' %>
	<%= button_link_to t(:'links.remove'), battle_path(@battle), method: :delete if current_codabra == @battle.creator %>
<% end %>